name: Daily Price Update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # Important! Full history laayega

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run Scraper
        run: python scraper.py

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          # Latest code pull karo
          git pull --rebase origin main

          # Diff add karo
          git add products.json

          # Agar koi change nahi hai to commit na kare
          git commit -m "Auto-update: Latest prices fetched" || exit 0

          # Push
          git push origin main
