- name: Checkout code
  uses: actions/checkout@v3
  with:
    fetch-depth: 0
    persist-credentials: true
name: Daily Price Update

on:
  schedule:
    - cron: '0 0 * * *' # Rozana raat 12 baje khud chalega
  workflow_dispatch: # Manually chalane ke liye

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run Scraper
        run: python scraper.py

      - name: Commit and Push changes
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add products.json
          git commit -m "Auto-update: Latest prices fetched" || echo "No changes to commit"
          # Integrate remote changes to avoid push rejection:
          git fetch origin main
          git pull --rebase origin main || git pull origin main || true
          # Push the update (no force)
          git push origin HEAD:main
