name: Daily Price Update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # Full history laayega
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Pull latest changes
        run: |
          git pull origin main --rebase || git pull origin main

      - name: Run Scraper
        run: python scraper.py

      - name: Commit and Push changes
        run: |
          # Check if there are any changes
          if [ -n "$(git status --porcelain)" ]; then
            git add products.json
            
            # Pull again before committing (in case something changed during scraping)
            git pull origin main --rebase || git pull origin main
            
            git commit -m "Auto-update: Latest prices fetched" || exit 0
            
            # Push with automatic retry on conflict
            git push origin main || {
              echo "Push failed, pulling latest and retrying..."
              git pull origin main --rebase
              git push origin main
            }
          else
            echo "No changes to commit"
          fi
